### ISSUE TITLE
KeyError: 'length'

### ISSUE THREAD

**Issue by taeheej** [neuralmagic/deepsparse#1020]
**Describe the bug**
KeyError: 'length'

**Expected behavior**
I tried to follow up the instruction of 'Dense Teacher Creation' in Question Answering

**Environment**
Include all relevant environment information:
1. OS [e.g. Ubuntu 18.04]: Ubunt 18.04
2. Python version [e.g. 3.7]:3.9
3. DeepSparse version or commit hash [e.g. 0.1.0, `f7245c8`]: 1.4.2
4. ML framework version(s) [e.g. torch 1.7.1]:torch 1.12.1
5. Other Python package versions [e.g. SparseML, Sparsify, numpy, ONNX]:sparseml-1.4.4, numpy-1.21.6, onnx-1.12.0
6. CPU info - output of deepsparse/src/deepsparse/arch.bin or output of cpu_architecture() as follows:
```python
>>> import deepsparse.cpu
>>> print(deepsparse.cpu.cpu_architecture())
```
{'L1_data_cache_size': 32768, 'L1_instruction_cache_size': 32768, 'L2_cache_size': 1048576, 'L3_cache_size': 37486592, 'architecture': 'x86_64', 'available_cores_per_socket': 24, 'available_num_cores': 48, 'available_num_hw_threads': 96, 'available_num_numa': 2, 'available_num_sockets': 2, 'available_sockets': 2, 'available_threads_per_core': 2, 'bf16': False, 'cores_per_socket': 24, 'dotprod': False, 'i8mm': False, 'isa': 'avx512', 'num_cores': 48, 'num_hw_threads': 96, 'num_numa': 2, 'num_sockets': 2, 'threads_per_core': 2, 'vendor': 'GenuineIntel', 'vendor_id': 'Intel', 'vendor_model': 'Intel(R) Xeon(R) Gold 6252 CPU @ 2.10GHz', 'vnni': True}

**To Reproduce**
sparseml.transformers.question_answering \
    --output_dir models/teacher \
    --model_name_or_path zoo:nlp/masked_language_modeling/bert-base/pytorch/huggingface/wikipedia_bookcorpus/base-none \
    --recipe zoo:nlp/masked_language_modeling/bert-base/pytorch/huggingface/wikipedia_bookcorpus/base-none?recipe_type=transfer-question_answering \
    --dataset_name squad --per_device_train_batch_size 16 --per_device_eval_batch_size 24 --preprocessing_num_workers 6 \
    --do_train --do_eval --evaluation_strategy epoch --fp16 --seed 42 \
    --per_device_train_batch_size 16 --per_device_eval_batch_size 24 \
    --save_strategy epoch --save_total_limit 1

Exact steps to reproduce the behavior:

**Errors**
Traceback (most recent call last):
  File "/wrk/xsjhdnobkup5/taeheej/anaconda3/envs/torch11/bin/sparseml.transformers.question_answering", line 8, in <module>
    sys.exit(main())
  File "/wrk/xsjhdnobkup5/taeheej/anaconda3/envs/torch11/lib/python3.9/site-packages/torch/distributed/elastic/multiprocessing/errors/__init__.py", line 345, in wrapper
    return f(*args, **kwargs)
  File "/wrk/xsjhdnobkup5/taeheej/anaconda3/envs/torch11/lib/python3.9/site-packages/sparseml/transformers/question_answering.py", line 422, in main
    raw_datasets = _get_raw_dataset(data_args=data_args, cache_dir=model_args.cache_dir)
  File "/wrk/xsjhdnobkup5/taeheej/anaconda3/envs/torch11/lib/python3.9/site-packages/sparseml/transformers/question_answering.py", line 904, in _get_raw_dataset
    raw_datasets = load_dataset(
  File "/wrk/xsjhdnobkup5/taeheej/anaconda3/envs/torch11/lib/python3.9/site-packages/datasets/load.py", line 1675, in load_dataset
    builder_instance = load_dataset_builder(
  File "/wrk/xsjhdnobkup5/taeheej/anaconda3/envs/torch11/lib/python3.9/site-packages/datasets/load.py", line 1533, in load_dataset_builder
    builder_instance: DatasetBuilder = builder_cls(
  File "/wrk/xsjhdnobkup5/taeheej/anaconda3/envs/torch11/lib/python3.9/site-packages/datasets/builder.py", line 1020, in __init__
    super().__init__(*args, **kwargs)
  File "/wrk/xsjhdnobkup5/taeheej/anaconda3/envs/torch11/lib/python3.9/site-packages/datasets/builder.py", line 290, in __init__
    self.info = DatasetInfo.from_directory(self._cache_dir)
  File "/wrk/xsjhdnobkup5/taeheej/anaconda3/envs/torch11/lib/python3.9/site-packages/datasets/info.py", line 250, in from_directory
    return cls.from_dict(dataset_info_dict)
  File "/wrk/xsjhdnobkup5/taeheej/anaconda3/envs/torch11/lib/python3.9/site-packages/datasets/info.py", line 255, in from_dict
    return cls(**{k: v for k, v in dataset_info_dict.items() if k in field_names})
  File "<string>", line 20, in __init__
  File "/wrk/xsjhdnobkup5/taeheej/anaconda3/envs/torch11/lib/python3.9/site-packages/datasets/info.py", line 141, in __post_init__
    self.features = Features.from_dict(self.features)
  File "/wrk/xsjhdnobkup5/taeheej/anaconda3/envs/torch11/lib/python3.9/site-packages/datasets/features/features.py", line 1271, in from_dict
    obj = generate_from_dict(dic)
  File "/wrk/xsjhdnobkup5/taeheej/anaconda3/envs/torch11/lib/python3.9/site-packages/datasets/features/features.py", line 1076, in generate_from_dict
    return {key: generate_from_dict(value) for key, value in obj.items()}
  File "/wrk/xsjhdnobkup5/taeheej/anaconda3/envs/torch11/lib/python3.9/site-packages/datasets/features/features.py", line 1076, in <dictcomp>
    return {key: generate_from_dict(value) for key, value in obj.items()}
  File "/wrk/xsjhdnobkup5/taeheej/anaconda3/envs/torch11/lib/python3.9/site-packages/datasets/features/features.py", line 1080, in generate_from_dict
    return Sequence(feature=generate_from_dict(obj["feature"]), length=obj["length"])
KeyError: 'length'

**Additional context**
I think this error is due to the version of datases, which is 1.18.4. (it is bound with sparsml)
This error might be resolved if datasets is upgrade  recent version.

**Comment by taeheej** [comment]
After I installed datasets 2.12.0 (recent version), the error is disappered.

**Comment by bfineran** [comment]
Thanks @taeheej. Closing this issue, monitoring internally to see if we need to upgrade across our repos.
