### ISSUE TITLE
conflict error

### ISSUE THREAD

**Issue by centurions** [neuralmagic/deepsparse#1105]
Hi . I get this error with this command : (Debian 11,Deepsparse 1.5.1)
deepsparse.benchmark ./yolov8n.onnx --scenario=sync --input_shapes="[1,3,640,640]"

Traceback (most recent call last):
  File "/home/ali/deep/bin/deepsparse.benchmark", line 5, in <module>
    from deepsparse.benchmark.benchmark_model import main
  File "/home/ali/deep/lib/python3.9/site-packages/deepsparse/__init__.py", line 36, in <module>
    from .pipeline import *
  File "/home/ali/deep/lib/python3.9/site-packages/deepsparse/pipeline.py", line 822, in <module>
    class PipelineConfig(BaseModel):
  File "/home/ali/deep/lib/python3.9/site-packages/pydantic/_internal/_model_construction.py", line 171, in __new__
    set_model_fields(cls, bases, config_wrapper, types_namespace)
  File "/home/ali/deep/lib/python3.9/site-packages/pydantic/_internal/_model_construction.py", line 361, in set_model_fields
    fields, class_vars = collect_model_fields(cls, bases, config_wrapper, types_namespace, typevars_map=typevars_map)
  File "/home/ali/deep/lib/python3.9/site-packages/pydantic/_internal/_fields.py", line 112, in collect_model_fields
    raise NameError(f'Field "{ann_name}" has conflict with protected namespace "{protected_namespace}"')
NameError: Field "model_path" has conflict with protected namespace "model_"

**Comment by jeanniefinks** [comment]
Hi @centurions 
Thank you for your message. We just pushed a hotfix to address this bug. Please see
[https://github.com/neuralmagic/deepsparse/releases](https://github.com/neuralmagic/deepsparse/releases)
May you install DeepSparse 1.5.2 and see if that clears your error?
Regards,  Jeannie / Neural Magic

**Comment by centurions** [comment]
Hi @jeanniefinks 
YESSS . It has been fixed . Thank You
