### ISSUE TITLE
pruned90_quant-none dataset download results in HTTP 403 Forbidden error

### ISSUE THREAD

**Issue by daveisdigital** [neuralmagic/deepsparse#1668]
**Describe the bug**
Example code attempts to download the pruned90_quant-none dataset. The webserver returns an HTTP 403 'Forbidden' error.

**Expected behavior**
The data should download and the example code should execute against it.

**Environment**
Include all relevant environment information:
1. OS [e.g. Ubuntu 18.04]: Rocky Linux 8.9
2. Python version [e.g. 3.8]: 3.6
3. DeepSparse version or commit hash [e.g. 0.1.0, `f7245c8`]: 
4. ML framework version(s) [e.g. torch 1.7.1]:
5. Other Python package versions [e.g. SparseML, Sparsify, numpy, ONNX]:
6. CPU info - output of deepsparse/src/deepsparse/arch.bin or output of cpu_architecture() as follows:
{'L1_data_cache_size': 32768, 'L1_instruction_cache_size': 32768, 'L2_cache_size': 1048576, 'L3_cache_size': 33554432, 'architecture': 'x86_64', 'available_cores_per_socket': 1, 'available_num_cores': 1, 'available_num_hw_threads': 1, 'available_num_numa': 1, 'available_num_sockets': 1, 'available_sockets': 1, 'available_threads_per_core': 1, 'cores_per_socket': 16, 'isa': 'avx512', 'num_cores': 16, 'num_hw_threads': 16, 'num_numa': 1, 'num_sockets': 1, 'threads_per_core': 1, 'vendor': 'AuthenticAMD', 'vendor_id': 'AMD', 'vendor_model': 'AMD EPYC 9R14', 'vnni': True}

**To Reproduce**
Example code from your github README:

[davei@daveiawsuseast2v3-c7a-4xlarge-0001 deepsparse-1.7.0]$ cat engine.py 
#!/usr/bin/env python3

from deepsparse import Engine

# download onnx, compile
zoo_stub = "zoo:nlp/sentiment_analysis/obert-base/pytorch/huggingface/sst2/pruned90_quant-none"
compiled_model = Engine(model=zoo_stub, batch_size=1)

# run inference (input is raw numpy tensors, output is raw scores)
inputs = compiled_model.generate_random_inputs()
output = compiled_model(inputs)
print(output)

# > [array([[-0.3380675 ,  0.09602544]], dtype=float32)] << raw scores

**Errors**
[davei@daveiawsuseast2v3-c7a-4xlarge-0001 deepsparse-1.7.0]$ ./engine.py 
Traceback (most recent call last):
  File "./engine.py", line 7, in <module>
    compiled_model = Engine(model=zoo_stub, batch_size=1)
  File "/home/davei/.local/lib/python3.6/site-packages/deepsparse/engine.py", line 184, in __init__
    self._model_path = model_to_path(model)
  File "/home/davei/.local/lib/python3.6/site-packages/deepsparse/utils/onnx.py", line 99, in model_to_path
    model = Model(model)
  File "/home/davei/.local/lib/python3.6/site-packages/sparsezoo/model/model.py", line 81, in __init__
    files, path, url = self.initialize_model_from_stub(self.source)
  File "/home/davei/.local/lib/python3.6/site-packages/sparsezoo/model/model.py", line 324, in initialize_model_from_stub
    stub, valid_params=list(PARAM_DICT.keys())
  File "/home/davei/.local/lib/python3.6/site-packages/sparsezoo/model/utils.py", line 98, in load_files_from_stub
    force_token_refresh=force_token_refresh,
  File "/home/davei/.local/lib/python3.6/site-packages/sparsezoo/utils/requests.py", line 120, in download_get_request
    response.raise_for_status()
  File "/home/davei/.local/lib/python3.6/site-packages/requests/models.py", line 960, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 403 Client Error: Forbidden for url: https://api.neuralmagic.com/models/download/nlp/sentiment_analysis/obert-base/pytorch/huggingface/sst2/pruned90_quant-none

**Additional context**
Add any other context about the problem here. Also include any relevant files.

**Comment by jeanniefinks** [comment]
Per the main [README announcement](https://github.com/neuralmagic/deepsparse/blob/main/README.md), DeepSparse is being deprecated by June 2, 2025. Closing the issue as further development has been suspended; thank you for the inputs and support!
