### ISSUE TITLE
Failed to deploy deepsparse in the cluster.

### ISSUE THREAD

**Issue by pacospace** [neuralmagic/deepsparse#186]
**Describe the bug**
Failed to deploy deepsparse in the cluster.

**Expected behavior**

**Environment**
Include all relevant environment information:
1. OS [e.g. Ubuntu 18.04]: ubi8
2. Python version [e.g. 3.7]: py38
3. DeepSparse version or commit hash [e.g. 0.1.0, `f7245c8`]: 0.7.0
4. ML framework version(s) [e.g. torch 1.7.1]: 
5. Other Python package versions [e.g. SparseML, Sparsify, numpy, ONNX]:
6. CPU info - output of deepsparse/src/deepsparse/arch.bin or output of cpu_architecture() as follows:
```python
>>> import deepsparse.cpu
>>> print(deepsparse.cpu.cpu_architecture())
```

**To Reproduce**
Image: https://quay.io/repository/thoth-station/neural-magic-deepsparse

**Errors**
```
[2021-09-29 16:26:02 +0000] [22] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/opt/app-root/lib64/python3.8/site-packages/gunicorn/arbiter.py", line 589, in spawn_worker
    worker.init_process()
  File "/opt/app-root/lib64/python3.8/site-packages/gunicorn/workers/base.py", line 134, in init_process
    self.load_wsgi()
  File "/opt/app-root/lib64/python3.8/site-packages/gunicorn/workers/base.py", line 146, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/opt/app-root/lib64/python3.8/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/opt/app-root/lib64/python3.8/site-packages/gunicorn/app/wsgiapp.py", line 58, in load
    return self.load_wsgiapp()
  File "/opt/app-root/lib64/python3.8/site-packages/gunicorn/app/wsgiapp.py", line 48, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/opt/app-root/lib64/python3.8/site-packages/gunicorn/util.py", line 359, in import_app
    mod = importlib.import_module(module)
  File "/usr/lib64/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/app-root/src/wsgi.py", line 61, in <module>
    from src.neural_magic_model import Model as NeuralMagicModel
  File "/opt/app-root/src/src/neural_magic_model.py", line 27, in <module>
    from deepsparse import compile_model
  File "/opt/app-root/lib64/python3.8/site-packages/deepsparse/__init__.py", line 28, in <module>
    from .engine import *
  File "/opt/app-root/lib64/python3.8/site-packages/deepsparse/engine.py", line 44, in <module>
    from deepsparse.lib import init_deepsparse_lib
  File "/opt/app-root/lib64/python3.8/site-packages/deepsparse/lib.py", line 27, in <module>
    CORES_PER_SOCKET, AVX_TYPE, VNNI = cpu_details()
  File "/opt/app-root/lib64/python3.8/site-packages/deepsparse/cpu.py", line 216, in cpu_details
    arch = cpu_architecture()
  File "/opt/app-root/lib64/python3.8/site-packages/deepsparse/cpu.py", line 167, in cpu_architecture
    raise OSError(
OSError: neuralmagic: cannot determine avx instruction set. Set NM_ARCH to one of avx2,avx512 to continue.

```

**Additional context**
Related-To: https://github.com/AICoE/elyra-aidevsecops-tutorial/issues/297

**Comment by bnellnm** [comment]
Hi @pacospace, the engine will fail to install on machines that don't support the avx2 or avx512 instruction sets.  In some cases running in a docker or VM can confuse the architecture detection code when the underlying hardware does actually support one of these instruction sets.   Can you provide us with some more information about the machine you are trying to install on?  e.g. CPU type/version, whether or not you are running a VM/docker and the contents of /proc/cpuinfo (if available).

**Comment by pacospace** [comment]
> Hi @pacospace, the engine will fail to install on machines that don't support the avx2 or avx512 instruction sets. In some cases running in a docker or VM can confuse the architecture detection code when the underlying hardware does actually support one of these instruction sets. Can you provide us with some more information about the machine you are trying to install on? e.g. CPU type/version, whether or not you are running a VM/docker and the contents of /proc/cpuinfo (if available).

Thanks for reaching out @bnellnm 

I'm using Openshift on Operate First ( https://www.operate-first.cloud/) in the smaug cluster. The deepsparse image linked above is an s2i container based on ubi8 python 3.8. 

I already checked `/proc/cpuinfo` and unfortunately none of the nodes reports flags with those instructions sets at the moment. I opened two features requests in Operate First to obtain a view of the flags from the nodes (https://github.com/operate-first/support/issues/409) and have Node Feature Discovery Operator (https://github.com/operate-first/support/issues/408) deployed to configure deployment on certain nodes with those flags if any. 
I will send tomorrow more info on the output of `/proc/cpuinfo`

Is there a method in deepsparse to check which instructions sets are supported/should be used for deployment for certain models? I'm thinking to automate all this process with those new features.

Thanks you a lot.

**Comment by bnellnm** [comment]
Hi @pacospace , the engine currently only supports avx2 and avx512 (and avx512 with optional vnni instructions).  avx512 is better supported in general and especially so for quantized networks when vnni is available.

**Comment by pacospace** [comment]
> Hi @pacospace , the engine currently only supports avx2 and avx512 (and avx512 with optional vnni instructions). avx512 is better supported in general and especially so for quantized networks when vnni is available.

CPU is:

```
vendor_id       : GenuineIntel
cpu family      : 6
model           : 45
model name      : Intel(R) Xeon(R) CPU E5-2660 0 @ 2.20GHz
```

**Comment by pacospace** [comment]
> Hi @pacospace , the engine currently only supports avx2 and avx512 (and avx512 with optional vnni instructions). avx512 is better supported in general and especially so for quantized networks when vnni is available.

Good to know thanks! I will test in a cluster with:
```
vendor_id       : GenuineIntel
cpu family      : 6
model           : 85
model name      : Intel Xeon Processor (Cascadelake)
```

which has `avx512_vnni` flag

**Comment by pacospace** [comment]
> > Hi @pacospace , the engine currently only supports avx2 and avx512 (and avx512 with optional vnni instructions). avx512 is better supported in general and especially so for quantized networks when vnni is available.
> 
> Good to know thanks! I will test in a cluster with:
> 
> ```
> vendor_id       : GenuineIntel
> cpu family      : 6
> model           : 85
> model name      : Intel Xeon Processor (Cascadelake)
> ```
> 
> which has `avx512_vnni` flag

```
---> Serving application with gunicorn (wsgi) ...
[2021-10-05 08:52:20 +0000] [1] [INFO] Starting gunicorn 20.1.0
[2021-10-05 08:52:20 +0000] [1] [INFO] Listening at: http://0.0.0.0:8080 (1)
[2021-10-05 08:52:20 +0000] [1] [INFO] Using worker: sync
[2021-10-05 08:52:20 +0000] [22] [INFO] Booting worker with pid: 22
DeepSparse Engine, Copyright 2021-present / Neuralmagic, Inc. version: 0.7.0 (62e7d51d) (release) (optimized) (system=avx512, binary=avx512)
172.22.42.1 - - [05/Oct/2021:08:52:28 +0000] "GET /readiness HTTP/1.1" 200 38 "-" "kube-probe/1.20"
```

ok all good!! nice!! Thanks @bnellnm!

**Comment by convertthinking** [comment]
> Hi @pacospace , the engine currently only supports avx2 and avx512 (and avx512 with optional vnni instructions). avx512 is better supported in general and especially so for quantized networks when vnni is available.

Why don't you switch according to the instruction set available?

If avx2 and avx512 are absent, you still can use SSE or AVX instructions, which are in fact not-so-much slower. Overall speed always affected by clocks, etc.

When you stop consider SSE, you are to throw away up to 24 cores/48 thread systems with up to 512Gb memory, when you stop consider AVX, you are to throw away some 48 cores/96 thread systems with up to 2Tb memory, which I believe is a complete waste while most of the powers are given by GPUs.
