### ISSUE TITLE
Cannot import deepsparse from WSL: cannot get cpu topology

### ISSUE THREAD

**Issue by clementpoiret** [neuralmagic/deepsparse#198]
**Describe the bug**

For testing purposes, I want to try if my code works on Windows Subsystem for Linux (WSL2). I'm using Ubuntu 18.04LTS.

Once on Ubuntu on WSL, I create a new python virtual env, then `pip install deepsparse`.

After that, while trying to import deepsparse I get:

```python
>>> import deepsparse
arch.bin: ./src/include/cpu_info/cpu_info.hpp:515: std::shared_ptr<cpu_info::topology> cpu_info::detect_topology_from_cpuid_api(): Assertion `!thread.exists' failed.
Traceback (most recent call last):
  File "/home/cp264607/mambaforge/envs/hsf/lib/python3.9/site-packages/deepsparse/cpu.py", line 119, in _parse_arch_bin
    info_str = subprocess.check_output(file_path).decode("utf-8")
  File "/home/cp264607/mambaforge/envs/hsf/lib/python3.9/subprocess.py", line 424, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/home/cp264607/mambaforge/envs/hsf/lib/python3.9/subprocess.py", line 528, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '/home/cp264607/mambaforge/envs/hsf/lib/python3.9/site-packages/deepsparse/arch.bin' died with <Signals.SIGABRT: 6>.
 
During handling of the above exception, another exception occurred:
 
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/cp264607/mambaforge/envs/hsf/lib/python3.9/site-packages/deepsparse/__init__.py", line 28, in <module>
    from .engine import *
  File "/home/cp264607/mambaforge/envs/hsf/lib/python3.9/site-packages/deepsparse/engine.py", line 44, in <module>
    from deepsparse.lib import init_deepsparse_lib
  File "/home/cp264607/mambaforge/envs/hsf/lib/python3.9/site-packages/deepsparse/lib.py", line 27, in <module>
    CORES_PER_SOCKET, AVX_TYPE, VNNI = cpu_details()
  File "/home/cp264607/mambaforge/envs/hsf/lib/python3.9/site-packages/deepsparse/cpu.py", line 216, in cpu_details
    arch = cpu_architecture()
  File "/home/cp264607/mambaforge/envs/hsf/lib/python3.9/site-packages/deepsparse/cpu.py", line 148, in cpu_architecture
    arch = _parse_arch_bin()
  File "/home/cp264607/mambaforge/envs/hsf/lib/python3.9/site-packages/deepsparse/cpu.py", line 47, in __call__
    self.memo[args] = self.f(*args)
  File "/home/cp264607/mambaforge/envs/hsf/lib/python3.9/site-packages/deepsparse/cpu.py", line 123, in _parse_arch_bin
    raise OSError(
OSError: neuralmagic: encountered exception while trying read arch.bin: Command '/home/cp264607/mambaforge/envs/hsf/lib/python3.9/site-packages/deepsparse/arch.bin' died with <Signals.SIGABRT: 6>.
```

**Expected behavior**

Maybe it should work on WSL :) 

**Environment**
Include all relevant environment information:
1. OS [e.g. Ubuntu 18.04]: Ubuntu 18.04LTS (On Windows 10, WSL2)
2. Python version [e.g. 3.7]: 3.9
3. DeepSparse version or commit hash [e.g. 0.1.0, `f7245c8`]: 0.8.0
4. ML framework version(s) [e.g. torch 1.7.1]: 1.10.0
5. Other Python package versions [e.g. SparseML, Sparsify, numpy, ONNX]:
6. CPU info - output of deepsparse/src/deepsparse/arch.bin or output of cpu_architecture() as follows:

This is basically what's not working

**To Reproduce**
Exact steps to reproduce the behavior:

1. On windows 10, activate WSL
2. Install Ubuntu 18.04 from microsoft store
3. On Ubuntu, create virtual env (I personnaly use mamba or conda)
4. pip install deepsparse
5. `import deepsparse`

**Errors**
If applicable, add a full print-out of any errors or exceptions that are raised or include screenshots to help explain your problem.

```python
>>> import deepsparse
arch.bin: ./src/include/cpu_info/cpu_info.hpp:515: std::shared_ptr<cpu_info::topology> cpu_info::detect_topology_from_cpuid_api(): Assertion `!thread.exists' failed.
Traceback (most recent call last):
  File "/home/cp264607/mambaforge/envs/hsf/lib/python3.9/site-packages/deepsparse/cpu.py", line 119, in _parse_arch_bin
    info_str = subprocess.check_output(file_path).decode("utf-8")
  File "/home/cp264607/mambaforge/envs/hsf/lib/python3.9/subprocess.py", line 424, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/home/cp264607/mambaforge/envs/hsf/lib/python3.9/subprocess.py", line 528, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '/home/cp264607/mambaforge/envs/hsf/lib/python3.9/site-packages/deepsparse/arch.bin' died with <Signals.SIGABRT: 6>.
 
During handling of the above exception, another exception occurred:
 
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/cp264607/mambaforge/envs/hsf/lib/python3.9/site-packages/deepsparse/__init__.py", line 28, in <module>
    from .engine import *
  File "/home/cp264607/mambaforge/envs/hsf/lib/python3.9/site-packages/deepsparse/engine.py", line 44, in <module>
    from deepsparse.lib import init_deepsparse_lib
  File "/home/cp264607/mambaforge/envs/hsf/lib/python3.9/site-packages/deepsparse/lib.py", line 27, in <module>
    CORES_PER_SOCKET, AVX_TYPE, VNNI = cpu_details()
  File "/home/cp264607/mambaforge/envs/hsf/lib/python3.9/site-packages/deepsparse/cpu.py", line 216, in cpu_details
    arch = cpu_architecture()
  File "/home/cp264607/mambaforge/envs/hsf/lib/python3.9/site-packages/deepsparse/cpu.py", line 148, in cpu_architecture
    arch = _parse_arch_bin()
  File "/home/cp264607/mambaforge/envs/hsf/lib/python3.9/site-packages/deepsparse/cpu.py", line 47, in __call__
    self.memo[args] = self.f(*args)
  File "/home/cp264607/mambaforge/envs/hsf/lib/python3.9/site-packages/deepsparse/cpu.py", line 123, in _parse_arch_bin
    raise OSError(
OSError: neuralmagic: encountered exception while trying read arch.bin: Command '/home/cp264607/mambaforge/envs/hsf/lib/python3.9/site-packages/deepsparse/arch.bin' died with <Signals.SIGABRT: 6>.
```

**Additional context**
Add any other context about the problem here. Also include any relevant files.

**Comment by Willtor** [comment]
That's an interesting one. My intuition is there's some incompatibility between Windows threads and pthreads that we hit in `arch.bin`. I'll have a look and see if there's anything glaringly obvious.

**Comment by Willtor** [comment]
Hi, Clément -- can you give us details about your hardware setup? One of our engineers tested on Windows 10 with Ubuntu 18.04 and Python 3.9.7 and `arch.bin` ran fine.

Also, could you try running `/home/cp264607/mambaforge/envs/hsf/lib/python3.9/site-packages/deepsparse/arch.bin` directly? If it works, it should just give you some simple JSON output and exit.

**Comment by Willtor** [comment]
Thanks! Is this an AWS instance? If so, which type? I'm going to try to replicate the environment to reproduce the bug.

**Comment by clementpoiret** [comment]
It's just a virtual machine on my Laptop, made with KVM on Arch Linux

**Comment by Willtor** [comment]
Ah! Okay. That's good to know. Are you able to run the examples, now?

**Comment by clementpoiret** [comment]
Yes, everything seems to be fine now :)
