### ISSUE TITLE
Use `deepsparse/examples/ultralytics-yolo/benchmark.py` to benchmark yolov5 base model with torch engine

### ISSUE THREAD

**Issue by SkalskiP** [neuralmagic/deepsparse#227]
Hello team. I was trying to use your yolov5 benchmarking script today, to compare fps achieved by default yolov5 model in pytorch and your optimized version running in deepsparse engine. Up until now, I was using your script to measure the performance of prooned and quantized models (as you may know as I was posting about it on your Slack) but I was using my own inference pipeline to measure the performance of the default yolov5 model. However, I'm starting to increasingly come to the conclusion that this comparison is unfair.

- In your benchmark you use input in a specific format and size which allows you to reliably compare results.
- I used video as input in my default yolov5 test. Today I accidentally made a test on another video and got radically different results. I'm starting to come to the conclusion that the resolution of the input video matters, because of the preprocessing that has to be done on each frame.

As a result, I decided to use your script, hoping that it will allow me to eliminate the variable - related to the input. And I tried using your script in this way:

```console
python benchmark.py \
    zoo:cv/detection/yolov5-s/pytorch/ultralytics/coco/base-none \
    --engine torch \
    --batch-size 1 \
    --num-iterations 500 \
    --num-warmup-iterations 100
```

Unfortunately, I was unsuccessful and the execution ended with an exception:

```
Loading torch model for zoo:cv/detection/yolov5-s/pytorch/ultralytics/coco/base-none
Traceback (most recent call last):
  File "benchmark.py", line 518, in <module>
    main()
  File "benchmark.py", line 514, in main
    benchmark_yolo(args)
  File "benchmark.py", line 448, in benchmark_yolo
    model, has_postprocessing = _load_model(args)
  File "benchmark.py", line 381, in _load_model
    model = torch.load(args.model_filepath)
  File "/opt/conda/lib/python3.8/site-packages/torch/serialization.py", line 658, in load
    with _open_file_like(f, 'rb') as opened_file:
  File "/opt/conda/lib/python3.8/site-packages/torch/serialization.py", line 231, in _open_file_like
    return _open_file(name_or_buffer, mode)
  File "/opt/conda/lib/python3.8/site-packages/torch/serialization.py", line 212, in __init__
    super(_open_file, self).__init__(open(name, mode))
FileNotFoundError: [Errno 2] No such file or directory: 'zoo:cv/detection/yolov5-s/pytorch/ultralytics/coco/base-none'
```

Is that by design? Wouldn't enabling such a benchmark make sense? Or am I just doing something wrong?

**Comment by mgoin** [comment]
Hi @SkalskiP, we definitely want to be able to run this kind of benchmark for you. To clarify that script is meant to benchmark between DeepSparse, ONNXRuntime, and Pytorch. For the first two you can use the SparseZoo model stub as you already are because they both take ONNX but for Pytorch you'll need to use their specific file type.

We have this distinction documented in the script in the help statement for the model path argument:
```
positional arguments:
  model_filepath        The full filepath of the ONNX model file or SparseZoo
                        stub to the model for deepsparse and onnxruntime
                        benchmarks. Path to a .pt loadable PyTorch Module for
                        torch benchmarks - the Module can be the top-level
                        object loaded or loaded into 'model' in a state dict
```
Or an example with yolov3 here
```
##########
Example for benchmarking on a local YOLOv3 PyTorch model on GPU with half precision:
python benchmark.py \
    /PATH/TO/yolov3-spp.pt \
    --engine torch \
    --batch-size 32 \
    --device cuda:0 \
    --half-precision
```

So for the [yolov5s base](https://sparsezoo.neuralmagic.com/models/cv%2Fdetection%2Fyolov5-s%2Fpytorch%2Fultralytics%2Fcoco%2Fbase-none) you've referenced above, you can download the `model.pt` from that SparseZoo page and then call the script like this

```
python benchmark.py \
    /PATH/TO/model.pt \
    --engine torch \
    --batch-size 1 \
    --num-iterations 500 \
    --num-warmup-iterations 100
```

**Comment by SkalskiP** [comment]
Hi @mgoin, thank you for clarifying. As I mentioned in the previous issue I'm off right now, but I'll be back in a week or so and will definitely look at it. It's a little unobvious that PyTorch inference doesn't work when you specify a stub, despite the fact that you're hosting the model. Perhaps I could prepare a PR modifying this script? If I understand correctly, the zip hosted under stub contains this .pt file?
