### ISSUE TITLE
Importing issue with raspberrypi 

### ISSUE THREAD

**Issue by AbdelsalamHaa** [neuralmagic/deepsparse#861]
**Describe the bug**
Can't import the package 

**Expected behavior**
imported like normal 
**Environment**
Include all relevant environment information:
1- Raspberrypi 4(64bit)
2. Python version :3.9.2
3. DeepSparse version or commit hash : latest 

**To Reproduce**
Exact steps to reproduce the behavior:

**Errors**
Traceback (most recent call last):
  File "/home/admin/.local/lib/python3.9/site-packages/deepsparse/cpu.py", line 130, in _parse_arch_bin
    info_str = subprocess.check_output(file_path).decode("utf-8")
  File "/usr/lib/python3.9/subprocess.py", line 424, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/usr/lib/python3.9/subprocess.py", line 505, in run
    with Popen(*popenargs, **kwargs) as process:
  File "/usr/lib/python3.9/subprocess.py", line 951, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib/python3.9/subprocess.py", line 1823, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
OSError: [Errno 8] Exec format error: '/home/admin/.local/lib/python3.9/site-packages/deepsparse/arch.bin'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/admin/Desktop/AI_test/deepSpars.py", line 2, in <module>
    from deepsparse import Pipeline
  File "/home/admin/.local/lib/python3.9/site-packages/deepsparse/__init__.py", line 33, in <module>
    from .engine import *
  File "/home/admin/.local/lib/python3.9/site-packages/deepsparse/engine.py", line 27, in <module>
    from deepsparse.benchmark import BenchmarkResults
  File "/home/admin/.local/lib/python3.9/site-packages/deepsparse/benchmark/__init__.py", line 17, in <module>
    from .ort_engine import *
  File "/home/admin/.local/lib/python3.9/site-packages/deepsparse/benchmark/ort_engine.py", line 49, in <module>
    ARCH = cpu_architecture()
  File "/home/admin/.local/lib/python3.9/site-packages/deepsparse/cpu.py", line 169, in cpu_architecture
    arch = _parse_arch_bin()
  File "/home/admin/.local/lib/python3.9/site-packages/deepsparse/cpu.py", line 51, in __call__
    self.memo[args] = self.f(*args)
  File "/home/admin/.local/lib/python3.9/site-packages/deepsparse/cpu.py", line 142, in _parse_arch_bin
    raise OSError(
OSError: Neural Magic: Encountered exception while trying read arch.bin: [Errno 8] Exec format error: '/home/admin/.local/lib/python3.9/site-packages/deepsparse/arch.bin'

**Comment by mgoin** [comment]
Hi @AbdelsalamHaa DeepSparse for ARM hasn't been released yet. Please be patient while we iron out the finishing touches in the coming weeks, it will be released on `[deepsparse-nightly](https://pypi.org/project/deepsparse-nightly/)` first
