### ISSUE TITLE
Unable to determine instruction set

### ISSUE THREAD

**Issue by SuroshAhmadZobair** [neuralmagic/deepsparse#920]
**Describe the bug**
I am trying to do inference on my custom model.onnx using deepsparse to lower the inference time on CPU. when i run 
`from deepsparse.pipelines.custom_pipeline import CustomTaskPipeline
`

the following error is **thrown** : 

'''Traceback (most recent call last):
  File "/home/ubuntu/anaconda3/envs/deepsparse/lib/python3.9/site-packages/deepsparse/cpu.py", line 130, in _parse_arch_bin
    info_str = subprocess.check_output(file_path).decode("utf-8")
  File "/home/ubuntu/anaconda3/envs/deepsparse/lib/python3.9/subprocess.py", line 424, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/home/ubuntu/anaconda3/envs/deepsparse/lib/python3.9/subprocess.py", line 528, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '/home/ubuntu/anaconda3/envs/deepsparse/lib/python3.9/site-packages/deepsparse/arch.bin' returned non-zero exit status 1.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/mnt/data/ubuntu/deepsparse/inference_deepsparse_yolov8.py", line 1, in <module>
    from deepsparse.pipelines.custom_pipeline import CustomTaskPipeline
  File "/home/ubuntu/anaconda3/envs/deepsparse/lib/python3.9/site-packages/deepsparse/__init__.py", line 33, in <module>
    from .engine import *
  File "/home/ubuntu/anaconda3/envs/deepsparse/lib/python3.9/site-packages/deepsparse/engine.py", line 27, in <module>
    from deepsparse.benchmark import BenchmarkResults
  File "/home/ubuntu/anaconda3/envs/deepsparse/lib/python3.9/site-packages/deepsparse/benchmark/__init__.py", line 17, in <module>
    from .ort_engine import *
  File "/home/ubuntu/anaconda3/envs/deepsparse/lib/python3.9/site-packages/deepsparse/benchmark/ort_engine.py", line 52, in <module>
    ARCH = cpu_architecture()
  File "/home/ubuntu/anaconda3/envs/deepsparse/lib/python3.9/site-packages/deepsparse/cpu.py", line 169, in cpu_architecture
    arch = _parse_arch_bin()
  File "/home/ubuntu/anaconda3/envs/deepsparse/lib/python3.9/site-packages/deepsparse/cpu.py", line 51, in __call__
    self.memo[args] = self.f(*args)
  File "/home/ubuntu/anaconda3/envs/deepsparse/lib/python3.9/site-packages/deepsparse/cpu.py", line 135, in _parse_arch_bin
    raise OSError(
OSError: Neural Magic: Encountered exception while trying read arch.bin: Unable to determine instruction set.'''

**Environment**
1. OS [ Ubuntu 22.04]:
2. Python version [3.9.16]:
4. ML framework version(s) [torch==1.12.1+cuda116]:
5. Other Python package versions [e.g. SparseML, Sparsify, numpy, ONNX]:
6. CPU info : Intel Xeon E5-1650 3.2GHz

**Comment by tlrmchlsmth** [comment]
Hi @SuroshAhmadZobair, it looks like DeepSparse is having trouble determining what hardware you're running on. Could you share the result of `lscpu`? 

Also it would be helpful to describe a bit more about the system that you're running on. E.g. are you running in a virtual machine or in some cloud instance?

**Comment by tlrmchlsmth** [comment]
Hi @SuroshAhmadZobair, I'm sorry but DeepSparse doesn't support your CPU. It requires AVX2 and FMA instructions, but the Xeon E5-1650 doesn't support these.
