### ISSUE TITLE
Cv2. Resize error yolov8 task in deepspatse. server onnx model

### ISSUE THREAD

**Issue by maheshs11** [neuralmagic/deepsparse#962]
#      result = self.fn(*self.args, **self.kwargs)
#    File "/deepsparse/src/deepsparse/yolo/pipelines.py", line 251, in _preprocess_image
#      image = cv2.resize(image, dsize=tuple(reversed(self.image_size)))
#  cv2.error: OpenCV(4.6.0) /io/opencv/modules/imgproc/src/resize.cpp:4055: error: (-215:Assertion failed) inv_scale_x > 0 in function 'resize'

**Comment by dbogunowicz** [comment]
Hey @mashesh11. I'd love to help you, but your issue description is very uninformative. Please rewrite it according to the suggested guidelines:

**Describe the bug**
A clear and concise description of what the bug is.

**Expected behavior**
A clear and concise description of what you expected to happen.

**Environment**
Include all relevant environment information:
1. OS [e.g. Ubuntu 18.04]:
2. Python version [e.g. 3.7]:
3. DeepSparse version or commit hash [e.g. 0.1.0, `f7245c8`]:
4. ML framework version(s) [e.g. torch 1.7.1]:
5. Other Python package versions [e.g. SparseML, Sparsify, numpy, ONNX]:
6. CPU info - output of deepsparse/src/deepsparse/arch.bin or output of cpu_architecture() as follows:
```python
>>> import deepsparse.cpu
>>> print(deepsparse.cpu.cpu_architecture())
```

**To Reproduce**
Exact steps to reproduce the behavior:


**Errors**
If applicable, add a full print-out of any errors or exceptions that are raised or include screenshots to help explain your problem.

**Additional context**
Add any other context about the problem here. Also include any relevant files.

**Comment by maheshs11** [comment]
# uname -a (os)

Linux 407c52636e09 5.10.102.1-microsoft-standard-WSL2 #1 SMP Wed Mar 2 00:30:59 UTC 2022 x86_64 GNU/Linux


#python=3.8.16


Deep Sparse version

-e git+https://github.com/neuralmagic/deepsparse.git@98986288c64a6b8ccc414e3bf6ed640dbe8b5079#egg=deepsparse_nightly


# pip freeze

absl-py==1.4.0

anyio==3.6.2

cachetools==5.3.0

certifi==2022.12.7

charset-normalizer==3.1.0

click==8.1.3

coloredlogs==15.0.1

contourpy==1.0.7

cycler==0.11.0

-e git+https://github.com/neuralmagic/deepsparse.git@98986288c64a6b8ccc414e3bf6ed640dbe8b5079#egg=deepsparse_nightly

fastapi==0.86.0

flatbuffers==23.3.3

fonttools==4.39.0

google-auth==2.16.2

google-auth-oauthlib==0.4.6

grpcio==1.51.3

h11==0.14.0

humanfriendly==10.0

idna==3.4

importlib-metadata==6.0.0

importlib-resources==5.12.0

kiwisolver==1.4.4

Markdown==3.4.1

MarkupSafe==2.1.2

matplotlib==3.7.1

mpmath==1.2.1

numpy==1.21.6

nvidia-ml-py==11.525.84

nvitop==1.0.0

oauthlib==3.2.2

onnx==1.12.0

onnxruntime==1.14.1

onnxruntime-gpu==1.14.1

opencv-python==4.6.0.66

packaging==23.0

pandas==1.5.3

Pillow==9.4.0

prometheus-client==0.16.0

protobuf==3.20.1

psutil==5.9.4

pyasn1==0.4.8

pyasn1-modules==0.2.8

pydantic==1.10.5

pyparsing==3.0.9

python-dateutil==2.8.2

python-multipart==0.0.6

pytz==2022.7.1

PyYAML==6.0

requests==2.28.2

requests-oauthlib==1.3.1

rsa==4.9

scipy==1.10.1

seaborn==0.12.2

sentry-sdk==1.16.0

six==1.16.0

sniffio==1.3.0

sparsezoo-nightly==1.5.0.20230301

starlette==0.20.4

sympy==1.11.1

tensorboard==2.12.0

tensorboard-data-server==0.7.0

tensorboard-plugin-wit==1.8.1

termcolor==2.2.0

thop==0.1.1.post2209072238

torch==1.12.0

torchvision==0.13.0

tqdm==4.65.0

typing_extensions==4.5.0

ultralytics==8.0.50

urllib3==1.26.14

uvicorn==0.20.0

Werkzeug==2.2.3

zipp==3.15.0

# Train settings -------------------------------------------------------------------------------------------------------

model: [yolov5s.pt](http://yolov5s.pt/) # path to model file, i.e. [yolov8n.pt](http://yolov8n.pt/), yolov8n.yaml

data: config_train/PPEquipment.yolov5pytorch/data.yaml # path to data file, i.e. i.e. coco128.yaml /opt/program/config_train/smdComponents.v6_yolov5pytorch/train/images

epochs: 500  # number of epochs to train for


# Export settings ------------------------------------------------------------------------------------------------------

format: onnx  # format to export to

keras: False  # use Keras

optimize: False  # TorchScript: optimize for mobile

int8: False  # CoreML/TF INT8 quantization

dynamic: True  # ONNX/TF/TensorRT: dynamic axes

simplify: False  # ONNX: simplify model

opset: 13  # ONNX: opset version (optional)

workspace: 4  # TensorRT: workspace size (GB)

nms: False  # CoreML: add NMS


#server config

num_cores: 5

num_workers: 8

engine_type: deepsparse

#context: MultiModelEngine

endpoints:

    - task: yolov8

      route: /model_001/predict

      model: models/model1/best.onnx


#error 


 Traceback (most recent call last):

   File "/usr/local/lib/python3.8/site-packages/starlette/middleware/base.py", line 43, in call_next

     message = await recv_stream.receive()

   File "/usr/local/lib/python3.8/site-packages/anyio/streams/memory.py", line 114, in receive

     raise EndOfStream

 anyio.EndOfStream


 During handling of the above exception, another exception occurred:


 Traceback (most recent call last):

   File "/usr/local/lib/python3.8/site-packages/uvicorn/protocols/http/h11_impl.py", line 407, in run_asgi

     result = await app(  # type: ignore[func-returns-value]

   File "/usr/local/lib/python3.8/site-packages/uvicorn/middleware/proxy_headers.py", line 78, in __call__

     return await [self.app](http://self.app/)(scope, receive, send)

   File "/usr/local/lib/python3.8/site-packages/fastapi/applications.py", line 270, in __call__

     await super().__call__(scope, receive, send)

   File "/usr/local/lib/python3.8/site-packages/starlette/applications.py", line 124, in __call__

     await self.middleware_stack(scope, receive, send)

   File "/usr/local/lib/python3.8/site-packages/starlette/middleware/errors.py", line 184, in __call__

     raise exc

   File "/usr/local/lib/python3.8/site-packages/starlette/middleware/errors.py", line 162, in __call__

     await [self.app](http://self.app/)(scope, receive, _send)

   File "/usr/local/lib/python3.8/site-packages/starlette/middleware/base.py", line 72, in __call__

     response = await self.dispatch_func(request, call_next)

   File "/deepsparse/src/deepsparse/server/system_logging.py", line 57, in dispatch

     response = await call_next(request)

   File "/usr/local/lib/python3.8/site-packages/starlette/middleware/base.py", line 46, in call_next

     raise app_exc

   File "/usr/local/lib/python3.8/site-packages/starlette/middleware/base.py", line 36, in coro

     await [self.app](http://self.app/)(scope, request.receive, send_stream.send)

   File "/usr/local/lib/python3.8/site-packages/starlette/middleware/exceptions.py", line 75, in __call__

     raise exc

   File "/usr/local/lib/python3.8/site-packages/starlette/middleware/exceptions.py", line 64, in __call__

     await [self.app](http://self.app/)(scope, receive, sender)

   File "/usr/local/lib/python3.8/site-packages/fastapi/middleware/asyncexitstack.py", line 21, in __call__

     raise e

   File "/usr/local/lib/python3.8/site-packages/fastapi/middleware/asyncexitstack.py", line 18, in __call__

     await [self.app](http://self.app/)(scope, receive, send)

   File "/usr/local/lib/python3.8/site-packages/starlette/routing.py", line 680, in __call__

     await route.handle(scope, receive, send)

   File "/usr/local/lib/python3.8/site-packages/starlette/routing.py", line 275, in handle

     await [self.app](http://self.app/)(scope, receive, send)

   File "/usr/local/lib/python3.8/site-packages/starlette/routing.py", line 65, in app

     response = await func(request)

   File "/usr/local/lib/python3.8/site-packages/fastapi/routing.py", line 235, in app

     raw_response = await run_endpoint_function(

   File "/usr/local/lib/python3.8/site-packages/fastapi/routing.py", line 163, in run_endpoint_function

     return await run_in_threadpool(dependant.call, **values)

   File "/usr/local/lib/python3.8/site-packages/starlette/concurrency.py", line 41, in run_in_threadpool

     return await anyio.to_thread.run_sync(func, *args)

   File "/usr/local/lib/python3.8/site-packages/anyio/to_thread.py", line 31, in run_sync

     return await get_asynclib().run_sync_in_worker_thread(

   File "/usr/local/lib/python3.8/site-packages/anyio/_backends/_asyncio.py", line 937, in run_sync_in_worker_thread

     return await future

   File "/usr/local/lib/python3.8/site-packages/anyio/_backends/_asyncio.py", line 867, in run

     result = context.run(func, *args)

   File "/deepsparse/src/deepsparse/server/server.py", line 270, in _predict_from_files

     return _predict(request)

   File "/deepsparse/src/deepsparse/server/server.py", line 257, in _predict

     pipeline_outputs = pipeline(request)

   File "/deepsparse/src/deepsparse/pipeline.py", line 242, in __call__

     engine_inputs: List[numpy.ndarray] = self.process_inputs(pipeline_inputs)

   File "/deepsparse/src/deepsparse/yolo/pipelines.py", line 191, in process_inputs

     image_batch = list(self.executor.map(self._preprocess_image, inputs.images))

   File "/usr/local/lib/python3.8/concurrent/futures/_base.py", line 619, in result_iterator

     yield fs.pop().result()

   File "/usr/local/lib/python3.8/concurrent/futures/_base.py", line 444, in result

     return self.__get_result()

   File "/usr/local/lib/python3.8/concurrent/futures/_base.py", line 389, in __get_result

     raise self._exception

   File "/usr/local/lib/python3.8/concurrent/futures/thread.py", line 57, in run

     result = self.fn(*self.args, **self.kwargs)

   File "/deepsparse/src/deepsparse/yolo/pipelines.py", line 251, in _preprocess_image

     image = cv2.resize(image, dsize=tuple(reversed(self.image_size)))

 cv2.error: OpenCV(4.6.0) /io/opencv/modules/imgproc/src/resize.cpp:4055: error: (-215:Assertion failed) inv_scale_x > 0 in function 'resize'

**Comment by dbogunowicz** [comment]
Could you check whether the image path is correct or not? if the path is incorrect, the image might be null and report an error while resizing. Could you add a line before `/deepsparse/src/deepsparse/yolo/pipelines.py", line 251, in _preprocess_image` to check whether the image is read successfully? 
```python
assert img!=None, "Image reading error. Check whether your image path is correct or not."
```
If this is the case, please double-check your image path.

**Comment by maheshs11** [comment]
if image.ndim < 4:
            # Assume a batch is of the correct size already
            print("image",image,len(image))
            image = cv2.resize(image, dsize=tuple(reversed(self.image_size)) 
Image is not empty. 
2023-03-20 12:44:51 deepsparse.server.server INFO     Initializing pipeline for 'yolov8-1'
[nm_ort 7fcf837d7740 >WARN<  is_supported_graph /home/ubuntu/build/nyann/src/onnxruntime_neuralmagic/supported/ops.cc:134] Warning: Optimized runtime disabled - Detected dynamic input images dim 2. Set inputs to static shapes to enable optimal performance.
2023-03-20 12:44:51 deepsparse.server.server INFO     Adding endpoints for 'yolov8-1'
2023-03-20 12:44:51 deepsparse.server.server INFO     Added '/model_002/predict' endpoint
2023-03-20 12:44:51 deepsparse.server.server INFO     Added '/model_002/predict/from_files' endpoint
2023-03-20 12:44:51 deepsparse.server.server INFO     Initializing pipeline for 'yolov8-2'
[nm_ort 7fcf837d7740 >WARN<  is_supported_graph /home/ubuntu/build/nyann/src/onnxruntime_neuralmagic/supported/ops.cc:134] Warning: Optimized runtime disabled - Detected dynamic input images dim 2. Set inputs to static shapes to enable optimal performance.
2023-03-20 12:44:52 deepsparse.server.server INFO     Adding endpoints for 'yolov8-2'
2023-03-20 12:44:52 deepsparse.server.server INFO     Added '/model_003/predict' endpoint
2023-03-20 12:44:52 deepsparse.server.server INFO     Added '/model_003/predict/from_files' endpoint
2023-03-20 12:44:52 deepsparse.server.server INFO     Added endpoints: ['/openapi.json', '/docs', '/docs/oauth2-redirect', '/redoc', '/', '/config', '/status', '/healthcheck', '/health', '/ping', '/endpoints', '/endpoints', '/model_001/predict', '/model_001/predict/from_files', '/model_002/predict', '/model_002/predict/from_files', '/model_003/predict', '/model_003/predict/from_files']
INFO:     Started server process [437]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
INFO:     Uvicorn running on http://0.0.0.0:5544/ (Press CTRL+C to quit)
INFO:     [172.28.0.1:42768](http://172.28.0.1:42768/) - "GET / HTTP/1.1" 307 Temporary Redirect
INFO:     [172.28.0.1:42768](http://172.28.0.1:42768/) - "GET /docs HTTP/1.1" 200 OK
INFO:     [172.28.0.1:42768](http://172.28.0.1:42768/) - "GET /openapi.json HTTP/1.1" 200 OK
image [[[ 2  5 12]
  [ 2  5 10]
  [ 4  5  9]
  ...
  [ 4  5  7]
  [ 4  6  5]
  [ 4  6  5]]

 [[ 1  4 11]
  [ 1  4  9]
  [ 3  4  8]
  ...
  [ 3  4  6]
  [ 3  5  4]
  [ 3  5  4]]

 [[ 1  4 13]
  [ 1  4 11]
  [ 3  4  9]
  ...
  [ 3  4  6]
  [ 3  4  6]
  [ 3  4  6]]

 ...

 [[19 17 41]
  [13 11 33]
  [ 7  6 24]
  ...
  [43 38 70]
  [41 37 74]
  [37 32 72]]

 [[16 14 36]
  [11  9 30]
  [ 7  6 24]
  ...
  [45 40 72]
  [43 39 76]
  [36 34 73]]

 [[ 9  7 28]
  [10  9 27]
  [14 13 31]
  ...
  [49 46 77]
  [50 46 83]
  [42 40 79]]] 416
2023-03-20 12:45:50 deepsparse.server.system_logging ERROR    OpenCV(4.6.0) /io/opencv/modules/imgproc/src/resize.cpp:4055: error: (-215:Assertion failed) inv_scale_x > 0 in function 'resize'

INFO:     [172.28.0.1:42770](http://172.28.0.1:42770/) - "POST /model_003/predict/from_files HTTP/1.1" 500 Internal Server Error
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/anyio/streams/memory.py", line 94, in receive
    return self.receive_nowait()
  File "/usr/local/lib/python3.8/site-packages/anyio/streams/memory.py", line 89, in receive_nowait
    raise WouldBlock
anyio.WouldBlock

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/starlette/middleware/base.py", line 43, in call_next
    message = await recv_stream.receive()
  File "/usr/local/lib/python3.8/site-packages/anyio/streams/memory.py", line 114, in receive
    raise EndOfStream
anyio.EndOfStream

During handling of the above exception, another exception occurred:

**Comment by maheshs11** [comment]
@dbogunowicz , error was due to export settings, dynamic axis = True , simplify =True , opset =" ",  fixed with False, False, 13.
